#ifndef _RISCV_PRNG_H
#define _RISCV_PRNG_H

#include <stdint.h>
#include "common_driver_fn_64.h"

extern volatile uint64_t* prng;

#define RAND_NUM_VALID_DELAY 1 

#define PRNG_SEED_BITS_64   64
#define PRNG_SEED_BITS_128   128
#define PRNG_SEED_WORDS_64 (PRNG_SEED_BITS_64 / BITS_PER_WORD) //1
#define PRNG_SEED_WORDS_128 (PRNG_SEED_BITS_128 / BITS_PER_WORD) //2


#define PRNG_POLY64_BITS 64
#define PRNG_POLY128_BITS 128
#define PRNG_POLY64_WORDS (PRNG_POLY64_BITS / BITS_PER_WORD ) //1
#define PRNG_POLY128_WORDS (PRNG_POLY128_BITS / BITS_PER_WORD ) //2


#define PRNG_RANDNUM_BITS_64 64
#define PRNG_RANDNUM_BITS_128 128
#define PRNG_RANDNUM_WORDS_64 (PRNG_RANDNUM_BITS_64 / BITS_PER_WORD ) //1
#define PRNG_RANDNUM_WORDS_128 (PRNG_RANDNUM_BITS_128 / BITS_PER_WORD ) //1
#define RAND_NUM_VALID 1

#define PRNG_MODE_WORDS 1

#define SEED_INPUT_DONE 1

#define PRNG_SEED_BASE 0
#define PRNG_POLY128_BASE      2
#define PRNG_MODE_BASE      4
#define PRNG_POLY64_BASE      8

#define PRNG_RANDNUM64_BASE  9
#define PRNG_RANDNUM128_BASE  10

#define RAND_NUM_VALID_BASE      14

#define SEED_INPUT_DONE_BASE     26



int check_prng(); 
int read_prng_seed();

#endif